# Assignment 1 Group no. 6
### Project members: 
Mar Balibrea Rull, marbr@kth.se
Marcos Fern√°ndez Carbonell, marcosfc@kth.se
Tiger Huan Hu Zha, tigerz2@illinois.edu

### Declaration:
By submitting this solution, it is hereby declared that all individuals listed above have contributed to the solution, either with code that appear in the final solution below, or with code that has been evaluated and compared to the final solution, but for some reason has been excluded. It is also declared that all project members fully understand all parts of the final solution and can explain it upon request.

It is furthermore declared that the code below is a contribution by the project members only, and specifically that no part of the solution has been copied from any other source (except for lecture slides at the course ID2214) and no part of the solution has been provided by someone not listed as project member above.

It is furthermore declared that it has been understood that no other library/package than the Python 3 standard library, NumPy and pandas may be used in the solution for this assignment.

### Instructions
All assignments starting with number 1 below are mandatory. Satisfactory solutions
will give 1 point (in total). If they in addition are good (all parts work more or less 
as they should), completed on time (submitted before the deadline in Canvas) and according
to the instructions, together with satisfactory solutions of assignments starting with 
number 2 below, then the assignment will receive 2 points (in total).

It is highly recommended that you do not develop the code directly within the notebook
but that you copy the comments and test cases to your regular development environment
and only when everything works as expected, that you paste your functions into this
notebook, do a final testing (all cells should succeed) and submit the whole notebook 
(a single file) in Canvas (do not forget to fill in your group number and names above).

## Load NumPy and pandas

In [3]:
import numpy as np
import pandas as pd

## 1a. Create and apply normalization

In [4]:
# Insert the functions create_normalization and apply_normalization below (after the comments)
#
# Input to create_normalization:
# df: a dataframe (where the column names "CLASS" and "ID" have special meaning)
# normalizationtype: "minmax" (default) or "zscore"
#
# Output from create_normalization:
# df: a new dataframe, where each numeric value in a column has been replaced by a normalized value
# normalization: a mapping (dictionary) from each column name to a triple, consisting of
#                ("minmax",min_value,max_value) or ("zscore",mean,std)
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Consider columns of type "float" or "int" only (and which are not labeled "CLASS" or "ID"),
#         the other columns should remain unchanged
# Hint 3: Take a close look at the lecture slides on data preparation
def create_normalization(df, normalizationtype = "minmax"):
    
    # hints 1, 2
    _df = df.select_dtypes(include = ["float", "int"]).drop(columns = ["CLASS", "ID"])
    
    # hint 3
    if normalizationtype is "minmax":
        
        normalization = {col: (normalizationtype, _df[col].min(), _df[col].max()) for col in _df.columns}
    elif normalizationtype is "zscore":
        
        normalization = {col: (normalizationtype, _df[col].mean(), _df[col].std()) for col in _df.columns}
    
    df_out = apply_normalization(_df, normalization)
    return df_out, normalization
    
#
# Input to apply_normalization:
# df: a dataframe
# normalization: a mapping (dictionary) from column names to triples (see above)
#
# Output from apply_normalization:
# df: a new dataframe, where each numerical value has been normalized according to the mapping
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: For minmax-normalization, you may consider to limit the output range to [0,1]
def apply_normalization(df, normalization):
    
    df_out = df.copy()
    for col in normalization:
        a = normalization[col][1]
        b = normalization[col][2]
    
        # hint 3
        if normalization[col][0] is "minmax":
            
            df_out[col] = (df_out[col] - a)/(b - a) # using broadcasting
            # df_out[col] = df_out[col].apply(lambda x: (x - a)/(b - a)) # using lambda
            df_out[col].clip(0, 1, inplace = True)
        elif normalization[col][0] is "zscore":
    
            df_out[col] = df_out[col].apply(lambda x: (x - a)/b)
    return df_out

In [5]:
# Test your code (leave this part unchanged)

glass_train_df = pd.read_csv("glass_train.txt")

glass_test_df = pd.read_csv("glass_test.txt")

glass_train_norm, normalization = create_normalization(glass_train_df, normalizationtype = "minmax")
print("normalization:\n")
for f in normalization:
    print("{}:{}".format(f, normalization[f]))

glass_test_norm = apply_normalization(glass_test_df, normalization)
print("\nglass_test_norm:\n")
glass_test_norm

normalization:

RI:('minmax', 1.51131, 1.53125)
Na:('minmax', 10.73, 15.79)
Mg:('minmax', 0.0, 4.49)
Al:('minmax', 0.29, 3.04)
Si:('minmax', 69.81, 75.18)
K:('minmax', 0.0, 6.21)
Ca:('minmax', 5.43, 14.68)
Ba:('minmax', 0.0, 3.15)
Fe:('minmax', 0.0, 0.37)

glass_test_norm:

,ID,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,CLASS
0,101,0.262788,0.399209,0.634744,0.418182,0.644320,0.091787,0.363243,0.034921,0.594595,2
1,104,0.799398,0.606719,0.701559,0.134545,0.141527,0.012882,0.671351,0.000000,0.000000,2
2,44,0.541123,0.592885,0.855234,0.156364,0.363128,0.027375,0.465946,0.000000,0.000000,1
3,17,0.327482,0.385375,0.817372,0.316364,0.614525,0.098229,0.353514,0.000000,0.000000,1
4,81,0.231194,0.420949,0.783964,0.665455,0.530726,0.111111,0.274595,0.000000,0.000000,2
...,...,...,...,...,...,...,...,...,...,...,...
102,80,0.230191,0.413043,0.783964,0.585455,0.567970,0.111111,0.274595,0.000000,0.000000,2
103,141,0.280341,0.513834,0.788419,0.480000,0.508380,0.109501,0.289730,0.000000,0.000000,2
104,14,0.309428,0.420949,0.792873,0.356364,0.633147,0.086957,0.318919,0.000000,0.459459,1
105,132,0.743731,0.586957,0.000000,0.389091,0.266294,0.030596,0.865946,0.000000,0.270270,2
106,102,0.300401,0.320158,0.605791,0.487273,0.569832,0.112721,0.410811,0.000000,0.000000,2

### Comment on assumptions, things that do not work properly, etc.

## 1b. Create and apply imputation

In [8]:
# Insert the functions create_imputation and apply_imputation below (after the comments)
#
# Input to create_imputation:
# df: a dataframe (where the column names "CLASS" and "ID" have special meaning)
#
# Output from create_imputation:
# df: a new dataframe, where each missing numeric value in a column has been replaced by the mean of that column 
#     and each missing categoric value in a column has been replaced by the mode of that column
# imputation: a mapping (dictionary) from column name to value that has replaced missing values
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Handle columns of type "float" or "int" only (and which are not labeled "CLASS" or "ID") in one way
#         and columns of type "object" and "category" in other ways
# Hint 3: Consider using the pandas functions mean() and mode() respectively, as well as fillna
# Hint 4: In the rare case of all values in a column being missing, replace numeric values with 0,
#         object values with "" and category values with the first category (cat.categories[0])  
def create_imputation(df):
    
    df_tmp = df.copy()
    
    df_tmp_num = df_tmp.drop(["CLASS","ID"], axis=1, errors="ignore").select_dtypes(include=["int","float"]) # Select only numeric columns
    df_mean = pd.DataFrame(df_tmp_num.mean())
    df_tmp_num[(df_tmp_num.isna().all()).index[df_tmp_num.isna().all()]] = 0 # When all values are missing in a numeric column all values are replaced with by 0

    df_tmp_obj = df_tmp.drop(["CLASS","ID"], axis=1, errors="ignore").select_dtypes(include=["object","category"]) # Select only object and categorical columns
    df_mode = df_tmp_obj.mode().transpose()
    df_tmp_obj[(df_tmp_obj.isna().all()).index[df_tmp_obj.isna().all()]] = "" # When all values are missing in a object or categorical column all values are replaced by ""

    imputation = ((pd.concat([df_mean[0],df_mode[0]], axis=0)).fillna(0)).to_dict() # Create a mapping from column name to new value
    
    df_out = apply_imputation(df, imputation) # Apply imputation
    return df_out, imputation
    

#
# Input to apply_imputation:
# df: a dataframe
# imputation: a mapping (dictionary) from column name to value that should replace missing values
#
# Output from apply_imputation:
# df: a new dataframe, where each missing value has been replaced according to the mapping
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Consider using fillna
def apply_imputation(df, imputation):
    
    df_out = df.copy()
    df_out.fillna(value=imputation, inplace=True) # Replace NaN values accoding with the dictionary imputation
    return df_out

In [9]:
# Test your code (leave this part unchanged)

anneal_train_df = pd.read_csv("anneal_train.txt")
anneal_test_df = pd.read_csv("anneal_test.txt")

anneal_train_imp, imputation = create_imputation(anneal_train_df)
anneal_test_imp = apply_imputation(anneal_test_df,imputation)

print("Imputation:\n")
for f in imputation:
    print("{}:{}".format(f,imputation[f]))

print("\nNo. of replaced missing values in training data:\n{}".format(anneal_train_imp.count()-anneal_train_df.count()))
print("\nNo. of replaced missing values in test data:\n{}".format(anneal_test_imp.count()-anneal_test_df.count()))

Imputation:

carbon:3.859688195991091
hardness:13.084632516703786
formability:2.2517482517482517
strength:26.302895322939868
enamelability:1.7142857142857142
m:0
marvi:0
exptl:0
corr:0
jurofm:0
s:0
p:0
thick:1.1911937639198227
width:769.4917594654789
len:1229.293986636971
bore:35.18930957683742
packing:3.0
family:TN
product-type:C
steel:A
temper_rolling:T
condition:S
non-ageing:N
surface-finish:P
surface-quality:E
bc:Y
bf:Y
bt:Y
bw/me:B
bl:Y
chrom:C
phos:P
cbond:Y
ferro:Y
blue-bright-varn-clean:B
lustre:Y
shape:SHEET
oil:Y

No. of replaced missing values in training data:
family                    382
product-type                0
steel                      43
carbon                      0
hardness                    0
temper_rolling            374
condition                 160
formability               163
strength                    0
non-ageing                391
surface-finish            444
surface-quality           128
enamelability             442
bc                        448
bf                        401
bt                        411
bw/me                     349
bl                        377
m                         449
chrom                     432
phos                      447
cbond                     408
marvi                     449
exptl                     449
ferro                     433
corr                      449
blue-bright-varn-clean    445
lustre                    425
jurofm                    449
s                         449
p                         449
shape                       0
thick                       0
width                       0
len                         0
oil                       414
bore                        0
packing                   445
CLASS                       0
dtype: int64

No. of replaced missing values in test data:
family                    390
product-type                0
steel                      43
carbon                      0
hardness                    0
temper_rolling            387
condition                 143
formability               155
strength                    0
non-ageing                402
surface-finish            445
surface-quality           116
enamelability             440
bc                        449
bf                        368
bt                        413
bw/me                     338
bl                        372
m                         449
chrom                     440
phos                      444
cbond                     416
marvi                     449
exptl                     447
ferro                     435
corr                      449
blue-bright-varn-clean    447
lustre                    422
jurofm                    449
s                         449
p                         449
shape                       0
thick                       0
width                       0
len                         0
oil                       420
bore                        0
packing                   444
CLASS                       0
dtype: int64

### Comment on assumptions, things that do not work properly, etc.

## 1c. Create and apply discretization

In [10]:
# Insert the functions create_bins and apply_bins below
#
# Input to create_bins:
# df: a dataframe
# nobins: no. of bins (default = 10)
# bintype: either "equal-width" (default) or "equal-size" 
#
# Output from create_bins:
# df: a new dataframe, where each numeric feature value has been replaced by a categoric (corresponding to some bin)
# binning: a mapping (dictionary) from column name to bins (threshold values for the bin)
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Discretize columns of type "float" or "int" only (and which are not labeled "CLASS" or "ID")
# Hint 3: Consider using pd.cut and pd.qcut respectively, with labels=False, retbins=True and duplicates="drop"
#         (the last option will avoid errors when not enough bins can be created)
# Hint 4: Set all columns in the new dataframe to be of type "category"
# Hint 5: Set the categories of the discretized features to be [0,...,nobins-1]
# Hint 6: Change the first and the last element of each binning to -np.inf and np.inf respectively 

def create_bins(df, nobins = 10, bintype = "equal-width"):
    
    # hints 1, 2, 3
    _df = df.select_dtypes(include = ["float", "int"]).drop(columns = ["CLASS", "ID"])
    
    binning = {}
    for col in _df.columns:
        
        if bintype == "equal-width":
            
            res, bins = pd.cut(_df[col], nobins, retbins = True, labels = False, duplicates = "drop")
        elif bintype == "equal-size":
            
            res, bins = pd.qcut(_df[col], nobins, retbins = True, labels = False, duplicates = "drop")
            
        # hint 6
        bins[0] = -np.inf
        bins[-1] = np.inf
        
        binning[col] = tuple(bins)
        
    # hints 4, 5
    df_out = apply_bins(_df, binning)
    return df_out, binning

#
# Input to apply_bins:
# df: a dataframe
# binning: a mapping (dictionary) from column name to bins (threshold values for the bin)
#
# Output from apply_bins:
# df: a new dataframe, where each numeric feature value has been replaced by a categoric (corresponding to some bin)
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Consider using pd.cut 
# Hint 3: Set all columns in the new dataframe to be of type "category"
# Hint 4: Set the categories of the discretized features to be [0,...,nobins-1]
#

def apply_bins(df, binning):
    
    # hint 1
    df_out = df.copy()
    
    for col in binning:
        
        # hints 2, 3, 4
        df_out[col] = pd.DataFrame(pd.cut(df_out[col], binning[col], labels = False, duplicates = "drop"))
        df_out[col].astype("category") #.cat.set_categories(np.arange(len(list(binning.values())[0])))
    
    return df_out

In [11]:
# Test your code  (leave this part unchanged)

glass_train_df = pd.read_csv("glass_train.txt")

glass_test_df = pd.read_csv("glass_test.txt")

glass_train_disc, binning = create_bins(glass_train_df,nobins=10,bintype="equal-size")
print("binning:\n")
for f in binning:
    print("{}:{}".format(f,binning[f]))

glass_test_disc = apply_bins(glass_test_df,binning)
print("\nglass_test_disc:\n")
glass_test_disc

binning:

RI:(-inf, 1.515896, 1.51618, 1.516516, 1.516866, 1.5175299999999998, 1.517902, 1.518618, 1.520114, 1.521846, inf)
Na:(-inf, 12.73, 12.872, 13.0, 13.222000000000001, 13.38, 13.492, 13.793999999999999, 14.197999999999999, 14.82, inf)
Mg:(-inf, 1.8200000000000003, 3.188, 3.41, 3.476, 3.55, 3.61, 3.728, inf)
Al:(-inf, 0.906, 1.172, 1.23, 1.3480000000000003, 1.48, 1.54, 1.622, 1.8080000000000003, 2.094, inf)
Si:(-inf, 71.756, 72.196, 72.388, 72.72, 72.79, 72.966, 73.06, 73.208, 73.372, inf)
K:(-inf, 0.006000000000000085, 0.14800000000000005, 0.39, 0.54, 0.5760000000000001, 0.6, 0.6360000000000002, 0.67, inf)
Ca:(-inf, 7.978, 8.112, 8.338, 8.554, 8.67, 8.81, 9.032, 9.674000000000001, 10.924000000000001, inf)
Ba:(-inf, 0.7800000000000004, inf)
Fe:(-inf, 0.06200000000000003, 0.1180000000000001, 0.24, inf)

glass_test_disc:

      ID  RI  Na  Mg  Al  Si  K  Ca  Ba  Fe  CLASS
0    101   3   1   1   4   8  4   5   0   2      2
1    104   9   7   1   0   0  1   9   0   0      2
2     44   9   6   7   0   1  2   8   0   0      1
3     17   5   0   6   1   7  6   5   0   0      1
4     81   1   1   4   9   3  8   0   0   0      2
..   ...  ..  ..  ..  ..  .. ..  ..  ..  ..    ...
102   80   1   1   4   8   5  8   0   0   0      2
103  141   4   4   4   6   3  8   1   0   0      2
104   14   4   1   5   3   8  3   3   0   2      1
105  132   9   6   0   4   0  2   9   0   1      2
106  102   4   0   1   7   5  8   7   0   0      2

[107 rows x 11 columns]

### Comment on assumptions, things that do not work properly, etc.

## 1d. Divide a dataset into a training and a test set

In [12]:
# Insert the function split below
#
# Input to split:
# df: a dataframe
# testfraction: a float in the range (0,1) (default = 0.5)
#
# Output from split:
# trainingdf: a dataframe consisting of a random sample of (1-testfraction) of the rows in df
# testdf: a dataframe consisting of the rows in df that are not included in trainingdf
#
# Hint: You may use np.random.permutation(df.index) to get a permuted list of indexes where a 
#       prefix corresponds to the test instances, and the suffix to the training instances 

def split(df, testfraction = 0.5):
    
    # hint
    indexes = np.random.permutation(df.index)
    
    test_idx = indexes[:round(len(indexes)*testfraction)]
    train_idx = indexes[round(len(indexes)*testfraction):]
    
    return df.drop(test_idx), df.drop(train_idx)

In [13]:
# Test your code  (leave this part unchanged)

glass_df = pd.read_csv("glass.txt")

glass_train, glass_test = split(glass_df,testfraction=0.25)

print("Training IDs:\n{}".format(glass_train["ID"].values))

print("\nTest IDs:\n{}".format(glass_test["ID"].values))

print("\nOverlap: {}".format(set(glass_train["ID"]).intersection(set(glass_test["ID"]))))

Training IDs:
[  2   3   4   5   6   7   9  10  11  13  14  15  17  19  20  22  24  25
  26  28  30  31  32  33  34  35  36  38  39  40  42  43  46  47  48  49
  51  53  54  58  60  61  63  64  65  66  67  69  70  71  72  73  74  75
  77  79  80  81  82  83  87  88  89  90  91  93  95  96  97  98  99 100
 101 102 104 108 109 110 112 113 115 116 117 118 120 121 123 124 125 126
 128 129 130 131 133 134 135 137 138 141 142 143 144 146 147 148 150 151
 152 153 154 155 158 162 163 164 165 166 167 168 169 170 171 172 173 174
 175 177 178 179 180 181 182 183 184 185 186 188 189 190 191 192 193 194
 195 196 197 199 200 201 203 204 205 207 208 209 210 211 213 214]

Test IDs:
[  1   8  12  16  18  21  23  27  29  37  41  44  45  50  52  55  56  57
  59  62  68  76  78  84  85  86  92  94 103 105 106 107 111 114 119 122
 127 132 136 139 140 145 149 156 157 159 160 161 176 187 198 202 206 212]

Overlap: set()

### Comment on assumptions, things that do not work properly, etc.

## 1e. Calculate accuracy of a set of predictions

In [14]:
# Insert the function accuracy below
#
# Input to accuracy:
# df: a dataframe with class labels as column names and each row corresponding to
#     a prediction with estimated probabilities for each class
# correctlabels: an array (or list) of the correct class label for each prediction
#                (the number of correct labels must equal the number of rows in df)
#
# Output from accuracy:
# accuracy: the fraction of cases for which the predicted class label coincides with the correct label
#
# Hint: In case the label receiving the highest probability is not unique, you may
#       resolve that by picking the first (as ordered by the column names) or 
#       by randomly selecting one of the labels with highest probaility.

def accuracy(df, correctlabels):
    
    maximums = df.idxmax(axis = 1)
    acc = np.sum(maximums == correctlabels)
    
    return acc/df.shape[0]

In [15]:
# Test your code  (leave this part unchanged)

predictions = pd.DataFrame({"A":[0.5,0.5,0.5,0.25,0.25],"B":[0.5,0.25,0.25,0.5,0.25],"C":[0.0,0.25,0.25,0.25,0.5]})
predictions

      A     B     C
0  0.50  0.50  0.00
1  0.50  0.25  0.25
2  0.50  0.25  0.25
3  0.25  0.50  0.25
4  0.25  0.25  0.50

In [16]:
correctlabels = ["B","A","B","B","C"]

accuracy(predictions,correctlabels) # Note that depending on how ties are resolved the accuracy may be 0.6 or 0.8

0.6

### Comment on assumptions, things that do not work properly, etc.

## 2a. Create and apply one-hot encoding

In [17]:
# Insert the functions create_one_hot and apply_one_hot below
#
# Input to create_one_hot:
# df: a dataframe
#
# Output from create_one_hot:
# df: a new dataframe, where each categoric feature has been replaced by a set of binary features 
#    (as many new features as there are possible values)
# one_hot: a mapping (dictionary) from column name to a set of categories (possible values for the feature)
#
# Hint 1: First copy the input dataframe and modify the copy (the input dataframe should be kept unchanged)
# Hint 2: Consider columns of type "object" or "category" only (and which are not labeled "CLASS" or "ID")
# Hint 3: Consider creating new column names by merging the original column name and the categorical value
# Hint 4: Set all new columns to be of type "float"
# Hint 5: Do not forget to remove the original categoric feature

def create_one_hot(df):
    
    # hints 1, 2
    _df = df.select_dtypes(include = ["object", "category"]).drop(columns = ["CLASS", "ID"], errors = "ignore")
    _df = _df.astype("category")
    
    one_hot = {col: tuple(_df[col].cat.categories) for col in _df}
    df_out = apply_one_hot(df, one_hot)
    
    return df_out, one_hot

#
# Input to apply_one_hot:
# df: a dataframe
# one_hot: a mapping (dictionary) from column name to categories
#
# Output from apply_one_hot:
# df: a new dataframe, where each categoric feature has been replaced by a set of binary features
#
# Hint: See the above Hints

def apply_one_hot(df, one_hot):
    
    df_out = df.copy()
    
    # hint 3
    # new_cols = [col+"-"+cat for col in df.columns for cat in df[col].unique()]
    # df_out = pd.DataFrame(columns = new_cols)
    for col in one_hot:
        
        for cat in one_hot[col]:   
            
            # hint 4
            df_out[col+"-"+cat] = (df[col] == cat).astype("float")
        
        # hint 5
        df_out.drop(columns = col, inplace = True)
    
    return df_out

In [18]:
# Test your code  (leave this part unchanged)

tictactoe = pd.read_csv("tic-tac-toe.txt")

train_df, test_df = split(tictactoe) # Using your above function

new_train, one_hot = create_one_hot(train_df)

new_test = apply_one_hot(test_df,one_hot)
new_test

,CLASS,top-left-square-b,top-left-square-o,top-left-square-x,top-middle-square-b,top-middle-square-o,top-middle-square-x,top-right-square-b,top-right-square-o,top-right-square-x,...,middle-right-square-x,bottom-left-square-b,bottom-left-square-o,bottom-left-square-x,bottom-middle-square-b,bottom-middle-square-o,bottom-middle-square-x,bottom-right-square-b,bottom-right-square-o,bottom-right-square-x
0,positive,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,positive,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,positive,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8,positive,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
9,positive,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,negative,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
945,negative,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
946,negative,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
949,negative,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
954,negative,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

### Comment on assumptions, things that do not work properly, etc.

## 2b. Divide a dataset into a number of folds

In [19]:
# Insert the function folds below
#
# Input to folds:
# df: a dataframe
# nofolds: an integer greater than 1 (default = 10)
#
# Output from folds:
# folds: a list (of length = nofolds) dataframes consisting of random non-overlapping, 
#        approximately equal-sized subsets of the rows in df
#
# Hint: You may use np.random.permutation(df.index) to get a permuted list of indexes from which a 
#       prefix corresponds to the test instances, and the suffix to the training instances 

def folds(df, nofolds = 10):
    
    # gets the size of the majority of the first nofolds-1 folds:
    # (nofolds - df.shape[0] % nofolds) is what you have to sum to df.shape[0] to get the next number / nofolds
    fold_size = round((df.shape[0] + (nofolds - df.shape[0] % nofolds)) / nofolds)
    
    # hint
    indexes = np.random.permutation(df.index)
    idx = [indexes[i*fold_size: (i+1)*fold_size] for i in range(nofolds)]
    
    folds = [df.iloc[idx[i]] for i in range(nofolds)]
    
    return folds

In [20]:
# Test your code  (leave this part unchanged)

glass_df = pd.read_csv("glass.txt")

glass_folds = folds(glass_df,nofolds=5)

fold_sizes = [len(f) for f in glass_folds]

print("Fold sizes:{}\nTotal no. instances: {}".format(fold_sizes,sum(fold_sizes)))

Fold sizes:[43, 43, 43, 43, 42]
Total no. instances: 214

### Comment on assumptions, things that do not work properly, etc.

## 2c. Calculate Brier score of a set of predictions

In [21]:
# Insert the function brier_score below
#
# Input to brier_score:
# df: a dataframe with class labels as column names and each row corresponding to
#     a prediction with estimated probabilities for each class
# correctlabels: an array (or list) of the correct class label for each prediction
#                (the number of correct labels must equal the number of rows in df)
#
# Output from brier_score:
# brier_score: the average square error of the predicted probabilties 
#
# Hint: Compare each predicted vector to a vector for each correct label, which is all zeros except 
#       for at the index of the correct class. The index can be found using np.where(df.columns==l)[0] 
#       where l is the correct label.

def brier_score(df, correctlabels):
    
    cols = df.columns
    correct = [(l == cols).astype(float) for l in correctlabels]
    _df = pd.DataFrame(correct, columns = cols).subtract(df)**2
    
    return sum(_df.sum(axis = 1))/len(df)

In [22]:
# Test your code  (leave this part unchanged)

predictions = pd.DataFrame({"A":[0.5,0.5,0.5,0.25,0.25],"B":[0.5,0.25,0.25,0.5,0.25],"C":[0.0,0.25,0.25,0.25,0.5]})

correctlabels = ["B","A","B","B","C"]

brier_score(predictions, correctlabels)

0.5

### Comment on assumptions, things that do not work properly, etc.

## 2d. Calculate AUC of a set of predictions

In [23]:
# Insert the function auc below
#
# Input to auc:
# df: a dataframe with class labels as column names and each row corresponding to
#     a prediction with estimated probabilities for each class
# correctlabels: an array (or list) of the correct class label for each prediction
#                (the number of correct labels must equal the number of rows in df)
#
# Output from auc:
# auc: the weighted area under ROC curve
#
# Hint 1: Calculate the binary AUC first for each class label c, i.e., treating the
#         predicted probability of this class for each instance as a score; the positive
#         instances are the ones belonging to class c and the negative instances the rest
# Hint 2: When calculating the binary AUC, first find the scores of the positive instances and then
#         the scores of the negative instances
# Hint 3: You may use a dictionary with a mapping from each score to an array of two numbers; 
#         the number of positive instances with this score and the number of negative instances with this score
# Hint 4: Created a (reversely) sorted (on the scores) list of pairs from the dictionary and
#         iterate over this to additively calculate the AUC
# Hint 5: For each pair in the above list, there are three cases to consider; the no. of true positives
#         (tp_i) is zero, the number of false positives (fp_i) (negatives) is zero, and both are non-zero
# Hint 6: Calculate the weighted AUC by summing the individual AUCs weighted by the relative
#         frequency of each class (as estimated from the correct labels)

def auc(df, correctlabels):
    
    cols = df.columns
    correct = [(l == cols).astype("float") for l in correctlabels]
    c_df = pd.DataFrame(correct, columns = cols) # one hot

    # hint 1
    AUC = 0
    for col in df.columns:
        
        # hint 3
        pairs = {score: [0, 0] for score in df[col]} # [positive, negative]

        for r in range(len(df[col])):
            
            # hint 2
            score = df[col][r] # probability of class col row n
            is_positive = c_df[col][r] == 1
            pairs[score] = [pairs[score][0] + is_positive, pairs[score][1] + ~is_positive]

        # hints 4, 5
        sorted_list = np.array([pairs[score] for score in sorted(pairs, reverse = True)])
        tp = sorted_list[:, 0]
        fp = sorted_list[:, 1]

        AUC_tmp = 0
        cov_tp = 0
        tot_tp = sum(tp)
        tot_fp = sum(fp)
        
        # hint 6
        for i in range(len(tp)):
            
            if fp[i] == 0:
                
                cov_tp += tp[i]
            elif tp[i] == 0:
                
                AUC_tmp += (cov_tp/tot_tp)*(fp[i]/tot_fp)
            else:
                
                AUC_tmp += (cov_tp/tot_tp)*(fp[i]/tot_fp)+(tp[i]/tot_tp)*(fp[i]/tot_fp)/2
                cov_tp += tp[i]
                
        AUC += sum(c_df[col])/len(c_df)*AUC_tmp
    return AUC

In [24]:
# Test your code  (leave this part unchanged)

predictions = pd.DataFrame({"A":[0.9,0.9,0.6,0.55],"B":[0.1,0.1,0.4,0.45]})

correctlabels = ["A","B","B","A"]

auc(predictions,correctlabels)

0.375

In [25]:
predictions = pd.DataFrame({"A":[0.5,0.5,0.5,0.25,0.25],"B":[0.5,0.25,0.25,0.5,0.25],"C":[0.0,0.25,0.25,0.25,0.5]})

correctlabels = ["B","A","B","B","C"]

auc(predictions,correctlabels)

0.8499999999999999

### Comment on assumptions, things that do not work properly, etc.